### PR TITLE
Card component

### PR DESCRIPTION
**Pull request by MiheerTamkhane**

### CODE REVIEW

**Review by abhijeetekad — APPROVED** [review]

**Review by vijaytembugade — APPROVED** [review]
Looks good. Just try to make horizontal card responsive. Rest of the things are good.

**Comment by MiheerTamkhane** [comment]
> Looks good. Just try to make horizontal card responsive. Rest of the things are good.

yes. thanks vijay

**Review by MarkVed17 — APPROVED** [review]
These cards look good!

**Review by tanveertkd — APPROVED** [review]
Look good!

**Pull request merged**
