### PR TITLE
Image and input components

### PR DESCRIPTION
**Pull request by MiheerTamkhane**

### CODE REVIEW

**Comment by jayeshjain98** [comment]
Looks clean and if validation for input is working fine you can merge it.

**Review by horsemaker — APPROVED** [review]
Looks fine! 👍

**Review by manojasarsa — APPROVED** [review]
Looks good to me!

**Comment by MiheerTamkhane** [comment]
> Looks clean and if validation for input is working fine you can merge it.

Yup validation is working now, Thanks for suggession man.

**Pull request merged**
